### ISSUE TITLE
readme 中的插件模型开发指南外部链接无法访问

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/website-fc#11]
> 需要注意的是：上一个插件的出参(output)会作为下一个插件或者组件的入参。详情可查看 [插件模型开发指南](https://www.serverless-devs.com/sdm/serverless_package_model/3.package_model#%E6%8F%92%E4%BB%B6%E6%A8%A1%E5%9E%8B%E8%A7%84%E8%8C%83)

上述引用中的链接 404 了.

**Comment by heimanba** [comment]
fixed
