### ISSUE TITLE
缺少调试指导

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/website-fc#4]
Readme 中只介绍了在 pre-deploy 这个插槽使用 website-fc 插件, 但实际情况是用户难以在本地进行调试, 只能反复的将函数部署到集成测试环境, 并在线上的 IDE 查看或直接访问测试环境来判断是否正确的集成了 website-fc 插件.

建议:
+ [ ] 增加本地调试指导章节, 
    + [ ] 如何在 after-build 插槽使用 website-fc 插件以便预览文件位置的变动情况.
    + [ ] 如何在 s local start 启动沙箱环境时进行调试.
+ [x] 适当增加日志输出, 以便在 `s build --debug` 时能获取更多的运行日志.
+ [x] #5

**Comment by heimanba** [comment]
1. 在 after-build  插槽中做，不太好做，因为nodejs用户或者前端的项目，基本不会使用s build能力。会很自然的使用`npm run build`自己来做打包的动作
2. 启动s local start沙箱问题在于，现在的调试工具基于docker来做。对于很多新用户来说负担很重。而且简单的一个静态页面，直接发布上去更加轻量。当然调试的问题我们也在考虑更轻量的方案。比如 https://github.com/dherault/serverless-offline
