### ISSUE TITLE
建议在 index 找不到的时候抛异常

### ISSUE THREAD

**Issue by DevDengChao** [devsapp/website-fc#6]
建议在 index 找不到的时候抛异常， 终止集成不当的 deploy 流程，让用户在发布到云端前得到反馈。

**Comment by heimanba** [comment]
好建议！！！

**Comment by heimanba** [comment]
fixed

**Comment by DevDengChao** [comment]
> fixed

CI 没通过， 有一个测试用例假设用户设置了 index.htm 作为首页， 但测试用例没找到这个文件 🤣 , 记得修复测试用例。
